### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by ZephyrRaine** [ZephyrRaine/UNREAL_HACK#1]
- [ ] Un Player avec contrôles Hack & Slash (souris) et Animations (au minimum Idle et Course).
- [ ] Au moins un des personnages du jeu (Joueur/PNJ/IA) doit contenir des animations/mesh autres que celles/celui du mannequin Unreal. Ici aussi il faut au moins Idle et Course.
- [x] Un système d'inventaire avec Drag & Drop (vous pouvez reprendre le système vu en cours ou en créer un nouveau)
- [x] Au moins 3 types d'objets, avec attribution d'un mesh sur le personnage si ces objets sont équipés.
- [x] Au moins un Event dispatcher devra être utilisé, celui-ci doit établir une communication avec le Level Blueprint.
- [x] Un niveau plus grand que celui de base (au moins 2 fois plus grand) qui permet de tester l'intégralité de vos features.
- [ ] Un doc récapitulant l'ensemble de vos fonctionnalités avec le moyen de les retrouver dans le projet (nom des classes C++/BP) ainsi que les touches associées.
- [ ] Un Code C++/BP commenté
